### ISSUE TITLE
pc speakers segfaults

### ISSUE THREAD

**Issue by arschles** [davecheney/pc#2]
Found with a build from 0181dbfd66a746aee369629485ec47518f1c29b2

Repro steps:

1. run `pc refresh`
2. run `pc speakers`

Result:

```console
➜  pc git:(master) ✗ ./pc speakers
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1306a3c]

goroutine 1 [running]:
main.speakers(0x6a5)
	/Users/arschles/src/pc/speakers.go:32 +0x2ac
main.main()
	/Users/arschles/src/pc/pc.go:43 +0xec0
```

**Comment by davecheney** [comment]
I see the problem. That report will not run correctly until we reveal
the speakers names after shortlisting.
